services:
  db:
    image: postgres:17.6-bookworm
    container_name: db_postgres_lab2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data_lab2:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - pg_network_lab2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-lab_db2}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.8.0
    container_name: pgadmin4_lab2
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data_lab2:/var/lib/pgadmin
    networks:
      - pg_network_lab2
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_lab3
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin}@db:5432/${POSTGRES_DB:-lab_db2}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
    networks:
      - pg_network_lab2
    depends_on:
      db:
        condition: service_healthy
    command: ["uv", "run", "python", "main.py"]
    restart: unless-stopped

volumes:
  db_data_lab2:
  pgadmin_data_lab2:

networks:
  pg_network_lab2:
    driver: bridge
