services:
  db:
    image: postgres:17.6-bookworm
    container_name: db_postgres_lab2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data_lab2:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - pg_network_lab2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-lab_db2}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.8.0
    container_name: pgadmin4_lab2
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data_lab2:/var/lib/pgadmin
    networks:
      - pg_network_lab2
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_lab2
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_VHOST=local
    volumes:
      - rabbitmq_data:/data
    networks:
      - pg_network_lab2
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - pg_network_lab2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_lab3
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin}@db:5432/${POSTGRES_DB:-lab_db2}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-local}
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
      - REDIS_DECODE_RESPONSES=${REDIS_DECODE_RESPONSES:-true}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
      - ./producer.py:/app/producer.py
    networks:
      - pg_network_lab2
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_healthy
    command: ["uv", "run", "python", "main.py"]
    restart: unless-stopped

  rabbitmq_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq_worker_lab2
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin}@db:5432/${POSTGRES_DB:-lab_db2}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-local}
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
    volumes:
      - ./app:/app/app
      - ./rabbitmq_worker.py:/app/rabbitmq_worker.py
    networks:
      - pg_network_lab2
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    command: ["uv", "run", "python", "rabbitmq_worker.py"]
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler_lab2
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin}@db:5432/${POSTGRES_DB:-lab_db2}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-local}
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
      - REDIS_DECODE_RESPONSES=${REDIS_DECODE_RESPONSES:-true}
    volumes:
      - ./app:/app/app
    networks:
      - pg_network_lab2
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_healthy
      app:
        condition: service_started
    command: ["uv", "run", "taskiq", "scheduler", "app.scheduler:scheduler", "--skip-first-run"]
    restart: unless-stopped

  taskiq_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskiq_worker_lab2
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin}@db:5432/${POSTGRES_DB:-lab_db2}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-local}
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
      - REDIS_DECODE_RESPONSES=${REDIS_DECODE_RESPONSES:-true}
    volumes:
      - ./app:/app/app
    networks:
      - pg_network_lab2
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_healthy
      scheduler:
        condition: service_started
    command: ["uv", "run", "taskiq", "worker", "app.scheduler:broker"]
    restart: unless-stopped

volumes:
  db_data_lab2:
  pgadmin_data_lab2:
  rabbitmq_data:
  redis-data:

networks:
  pg_network_lab2:
    driver: bridge
